///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WordPress_Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddNewPost recording.
    /// </summary>
    [TestModule("cfe3bd8c-69dd-4835-a61a-3b03abc1dcb4", ModuleType.Recording, 1)]
    public partial class AddNewPost : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WordPress_WebRepository repository.
        /// </summary>
        public static WordPress_WebRepository repo = WordPress_WebRepository.Instance;

        static AddNewPost instance = new AddNewPost();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddNewPost()
        {
            var_title = "";
            var_content = "This is ";
            var_return_posted_link = "";
            var_return_title = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddNewPost Instance
        {
            get { return instance; }
        }

#region Variables

        string _var_title;

        /// <summary>
        /// Gets or sets the value of variable var_title.
        /// </summary>
        [TestVariable("e6361170-3a31-4e42-818e-1bd0a2a73b1e")]
        public string var_title
        {
            get { return _var_title; }
            set { _var_title = value; }
        }

        string _var_content;

        /// <summary>
        /// Gets or sets the value of variable var_content.
        /// </summary>
        [TestVariable("ed41f2e5-02b6-4b9b-abfd-a176858a8ada")]
        public string var_content
        {
            get { return _var_content; }
            set { _var_content = value; }
        }

        string _var_return_posted_link;

        /// <summary>
        /// Gets or sets the value of variable var_return_posted_link.
        /// </summary>
        [TestVariable("6448ddd1-565d-4a4b-86a1-4d8cc3037a58")]
        public string var_return_posted_link
        {
            get { return _var_return_posted_link; }
            set { _var_return_posted_link = value; }
        }

        string _var_return_title;

        /// <summary>
        /// Gets or sets the value of variable var_return_title.
        /// </summary>
        [TestVariable("86f44627-138b-421b-b40b-9f3070d2e944")]
        public string var_return_title
        {
            get { return _var_return_title; }
            set { _var_return_title = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible('5000ms') on item 'WordPress_Main_Page.posts_link'.", repo.WordPress_Main_Page.posts_linkInfo, new RecordItemIndex(0));
            repo.WordPress_Main_Page.posts_link.Element.InvokeActionWithText("EnsureVisible", "5000ms");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Main_Page.posts_link' at 69;15.", repo.WordPress_Main_Page.posts_linkInfo, new RecordItemIndex(1));
            repo.WordPress_Main_Page.posts_link.Click("69;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible('5000ms') on item 'WordPress_Main_Page.add_new_link'.", repo.WordPress_Main_Page.add_new_linkInfo, new RecordItemIndex(2));
            repo.WordPress_Main_Page.add_new_link.Element.InvokeActionWithText("EnsureVisible", "5000ms");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Main_Page.add_new_link' at 82;13.", repo.WordPress_Main_Page.add_new_linkInfo, new RecordItemIndex(3));
            repo.WordPress_Main_Page.add_new_link.Click("82;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible('5000ms') on item 'WordPress_Main_Page.title_tbx'.", repo.WordPress_Main_Page.title_tbxInfo, new RecordItemIndex(4));
            repo.WordPress_Main_Page.title_tbx.Element.InvokeActionWithText("EnsureVisible", "5000ms");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Main_Page.title_tbx' at 204;17.", repo.WordPress_Main_Page.title_tbxInfo, new RecordItemIndex(5));
            repo.WordPress_Main_Page.title_tbx.Click("204;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$var_title' with focus on 'WordPress_Main_Page.title_tbx'.", repo.WordPress_Main_Page.title_tbxInfo, new RecordItemIndex(6));
            repo.WordPress_Main_Page.title_tbx.PressKeys(var_title);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Value=$var_title) on item 'WordPress_Main_Page.title_tbx'.", repo.WordPress_Main_Page.title_tbxInfo, new RecordItemIndex(7));
                Validate.AttributeEqual(repo.WordPress_Main_Page.title_tbxInfo, "Value", var_title, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Value' from item 'WordPress_Main_Page.title_tbx' and assigning its value to variable 'var_return_title'.", repo.WordPress_Main_Page.title_tbxInfo, new RecordItemIndex(8));
            var_return_title = repo.WordPress_Main_Page.title_tbx.Element.GetAttributeValueText("Value");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Main_Page.content_tbx' at 49;25.", repo.WordPress_Main_Page.content_tbxInfo, new RecordItemIndex(9));
            repo.WordPress_Main_Page.content_tbx.Click("49;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible('5000ms') on item 'WordPress_Main_Page.content_tbx'.", repo.WordPress_Main_Page.content_tbxInfo, new RecordItemIndex(10));
            repo.WordPress_Main_Page.content_tbx.Element.InvokeActionWithText("EnsureVisible", "5000ms");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$var_content' with focus on 'WordPress_Main_Page.content_tbx'.", repo.WordPress_Main_Page.content_tbxInfo, new RecordItemIndex(11));
            repo.WordPress_Main_Page.content_tbx.PressKeys(var_content);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Value=$var_content) on item 'WordPress_Main_Page.content_tbx'.", repo.WordPress_Main_Page.content_tbxInfo, new RecordItemIndex(12));
                Validate.AttributeEqual(repo.WordPress_Main_Page.content_tbxInfo, "Value", var_content, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(12)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Main_Page.publish_btn' at 36;14.", repo.WordPress_Main_Page.publish_btnInfo, new RecordItemIndex(13));
            repo.WordPress_Main_Page.publish_btn.Click("36;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(14));
            Delay.Duration(5000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Post published. ') on item 'WordPress_Main_Page.post_published_message'.", repo.WordPress_Main_Page.post_published_messageInfo, new RecordItemIndex(15));
                Validate.AttributeEqual(repo.WordPress_Main_Page.post_published_messageInfo, "InnerText", "Post published. ", null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(15)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
