///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WordPress_Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeletePost recording.
    /// </summary>
    [TestModule("a19da4eb-b0c9-4b9a-bf2d-e8324826bf07", ModuleType.Recording, 1)]
    public partial class DeletePost : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WordPress_WebRepository repository.
        /// </summary>
        public static WordPress_WebRepository repo = WordPress_WebRepository.Instance;

        static DeletePost instance = new DeletePost();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeletePost()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeletePost Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible('5000ms') on item 'WordPress_Main_Page.edit_post_link'.", repo.WordPress_Main_Page.edit_post_linkInfo, new RecordItemIndex(0));
            repo.WordPress_Main_Page.edit_post_link.Element.InvokeActionWithText("EnsureVisible", "5000ms");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Main_Page.edit_post_link' at 35;17.", repo.WordPress_Main_Page.edit_post_linkInfo, new RecordItemIndex(1));
            repo.WordPress_Main_Page.edit_post_link.Click("35;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible('5000ms') on item 'WordPress_Main_Page.move_to_trash_link'.", repo.WordPress_Main_Page.move_to_trash_linkInfo, new RecordItemIndex(2));
            repo.WordPress_Main_Page.move_to_trash_link.Element.InvokeActionWithText("EnsureVisible", "5000ms");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Main_Page.move_to_trash_link' at 43;11.", repo.WordPress_Main_Page.move_to_trash_linkInfo, new RecordItemIndex(3));
            repo.WordPress_Main_Page.move_to_trash_link.Click("43;11");
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='1 post moved to the Trash. ') on item 'WordPress_Main_Page.remove_post_message'.", repo.WordPress_Main_Page.remove_post_messageInfo, new RecordItemIndex(4));
                Validate.AttributeEqual(repo.WordPress_Main_Page.remove_post_messageInfo, "InnerText", "1 post moved to the Trash. ", null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
