///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WordPress_Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("a1babbd3-37eb-438e-9253-107a9e12a62e", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WordPress_WebRepository repository.
        /// </summary>
        public static WordPress_WebRepository repo = WordPress_WebRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            var_username = "";
            var_password = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _var_username;

        /// <summary>
        /// Gets or sets the value of variable var_username.
        /// </summary>
        [TestVariable("b77cf8a9-b7fb-4d0f-8a8e-ad5ff39fcf02")]
        public string var_username
        {
            get { return _var_username; }
            set { _var_username = value; }
        }

        string _var_password;

        /// <summary>
        /// Gets or sets the value of variable var_password.
        /// </summary>
        [TestVariable("5929c5c0-658a-4f06-abc0-164c736bb66c")]
        public string var_password
        {
            get { return _var_password; }
            set { _var_password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'WordPress_Login_Page.login_tbx'.", repo.WordPress_Login_Page.login_tbxInfo, new RecordItemIndex(0));
            repo.WordPress_Login_Page.login_tbx.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'WordPress_Login_Page.login_tbx'.", repo.WordPress_Login_Page.login_tbxInfo, new RecordItemIndex(1));
            repo.WordPress_Login_Page.login_tbx.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Login_Page.login_tbx' at 75;23.", repo.WordPress_Login_Page.login_tbxInfo, new RecordItemIndex(2));
            repo.WordPress_Login_Page.login_tbx.Click("75;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(3));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$var_username' with focus on 'WordPress_Login_Page.login_tbx'.", repo.WordPress_Login_Page.login_tbxInfo, new RecordItemIndex(4));
            repo.WordPress_Login_Page.login_tbx.PressKeys(var_username);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'WordPress_Login_Page.password_tbx'.", repo.WordPress_Login_Page.password_tbxInfo, new RecordItemIndex(5));
            repo.WordPress_Login_Page.password_tbx.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'WordPress_Login_Page.password_tbx'.", repo.WordPress_Login_Page.password_tbxInfo, new RecordItemIndex(6));
            repo.WordPress_Login_Page.password_tbx.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Login_Page.password_tbx' at 66;19.", repo.WordPress_Login_Page.password_tbxInfo, new RecordItemIndex(7));
            repo.WordPress_Login_Page.password_tbx.Click("66;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(8));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$var_password' with focus on 'WordPress_Login_Page.password_tbx'.", repo.WordPress_Login_Page.password_tbxInfo, new RecordItemIndex(9));
            repo.WordPress_Login_Page.password_tbx.PressKeys(var_password);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'WordPress_Login_Page.login_btn' at Center.", repo.WordPress_Login_Page.login_btnInfo, new RecordItemIndex(10));
            repo.WordPress_Login_Page.login_btn.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Login_Page.login_btn' at 33;18.", repo.WordPress_Login_Page.login_btnInfo, new RecordItemIndex(11));
            repo.WordPress_Login_Page.login_btn.Click("33;18");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
