///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WordPress_Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyPostIsViewed recording.
    /// </summary>
    [TestModule("e77799ce-490d-41dc-84c8-30d2a56cca57", ModuleType.Recording, 1)]
    public partial class VerifyPostIsViewed : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WordPress_WebRepository repository.
        /// </summary>
        public static WordPress_WebRepository repo = WordPress_WebRepository.Instance;

        static VerifyPostIsViewed instance = new VerifyPostIsViewed();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyPostIsViewed()
        {
            var_blog_title = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyPostIsViewed Instance
        {
            get { return instance; }
        }

#region Variables

        string _var_blog_title;

        /// <summary>
        /// Gets or sets the value of variable var_blog_title.
        /// </summary>
        [TestVariable("36f63dca-6bfd-4112-abf3-6e94eb37d57e")]
        public string var_blog_title
        {
            get { return _var_blog_title; }
            set { _var_blog_title = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(0));
            Delay.Duration(5000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$var_blog_title) on item 'WordPress_Blog_Page.title_lbl'.", repo.WordPress_Blog_Page.title_lblInfo, new RecordItemIndex(1));
                Validate.AttributeEqual(repo.WordPress_Blog_Page.title_lblInfo, "InnerText", var_blog_title, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
