///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WordPress_Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ViewAddedPost recording.
    /// </summary>
    [TestModule("8c2bc23f-00b6-4c7e-a1f4-14ca532cb827", ModuleType.Recording, 1)]
    public partial class ViewAddedPost : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WordPress_WebRepository repository.
        /// </summary>
        public static WordPress_WebRepository repo = WordPress_WebRepository.Instance;

        static ViewAddedPost instance = new ViewAddedPost();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ViewAddedPost()
        {
            url_to_view = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ViewAddedPost Instance
        {
            get { return instance; }
        }

#region Variables

        string _url_to_view;

        /// <summary>
        /// Gets or sets the value of variable url_to_view.
        /// </summary>
        [TestVariable("1cbb4ec0-689d-4893-a69b-8046e1f8479e")]
        public string url_to_view
        {
            get { return _url_to_view; }
            set { _url_to_view = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible('5000ms') on item 'WordPress_Main_Page.view_post_btn'.", repo.WordPress_Main_Page.view_post_btnInfo, new RecordItemIndex(0));
            repo.WordPress_Main_Page.view_post_btn.Element.InvokeActionWithText("EnsureVisible", "5000ms");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Main_Page.view_post_btn' at 35;13.", repo.WordPress_Main_Page.view_post_btnInfo, new RecordItemIndex(1));
            repo.WordPress_Main_Page.view_post_btn.Click("35;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(2));
            Delay.Duration(5000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
