///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WordPress_Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WordPress_WebRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b93696aa-c975-459f-a9f8-c5ff11fcb831")]
    public partial class WordPress_WebRepository : RepoGenBaseFolder
    {
        static WordPress_WebRepository instance = new WordPress_WebRepository();
        WordPress_WebRepositoryFolders.WordPress_Login_PageAppFolder _wordpress_login_page;
        WordPress_WebRepositoryFolders.Chrome_WebAppFolder _chrome_web;
        WordPress_WebRepositoryFolders.WordPress_Main_PageAppFolder _wordpress_main_page;
        WordPress_WebRepositoryFolders.WordPress_Blog_PageAppFolder _wordpress_blog_page;

        /// <summary>
        /// Gets the singleton class instance representing the WordPress_WebRepository element repository.
        /// </summary>
        [RepositoryFolder("b93696aa-c975-459f-a9f8-c5ff11fcb831")]
        public static WordPress_WebRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WordPress_WebRepository() 
            : base("WordPress_WebRepository", "/", null, 0, false, "b93696aa-c975-459f-a9f8-c5ff11fcb831", ".\\RepositoryImages\\WordPress_WebRepositoryb93696aa.rximgres")
        {
            _wordpress_login_page = new WordPress_WebRepositoryFolders.WordPress_Login_PageAppFolder(this);
            _chrome_web = new WordPress_WebRepositoryFolders.Chrome_WebAppFolder(this);
            _wordpress_main_page = new WordPress_WebRepositoryFolders.WordPress_Main_PageAppFolder(this);
            _wordpress_blog_page = new WordPress_WebRepositoryFolders.WordPress_Blog_PageAppFolder(this);
        }

#region Variables

        string _var_posted_text = "";

        /// <summary>
        /// Gets or sets the value of variable var_posted_text.
        /// </summary>
        [TestVariable("fd0fc36d-a0f3-4630-8326-dbd419b438ad")]
        public string var_posted_text
        {
            get { return _var_posted_text; }
            set { _var_posted_text = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b93696aa-c975-459f-a9f8-c5ff11fcb831")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The WordPress_Login_Page folder.
        /// </summary>
        [RepositoryFolder("c5c0629b-cf07-4542-bacf-9ed51373a673")]
        public virtual WordPress_WebRepositoryFolders.WordPress_Login_PageAppFolder WordPress_Login_Page
        {
            get { return _wordpress_login_page; }
        }

        /// <summary>
        /// The Chrome_Web folder.
        /// </summary>
        [RepositoryFolder("adb87cfd-4e0a-4358-bd98-96f3a95b49cb")]
        public virtual WordPress_WebRepositoryFolders.Chrome_WebAppFolder Chrome_Web
        {
            get { return _chrome_web; }
        }

        /// <summary>
        /// The WordPress_Main_Page folder.
        /// </summary>
        [RepositoryFolder("f7e264bd-8534-45b8-965e-65fc2f86c78b")]
        public virtual WordPress_WebRepositoryFolders.WordPress_Main_PageAppFolder WordPress_Main_Page
        {
            get { return _wordpress_main_page; }
        }

        /// <summary>
        /// The WordPress_Blog_Page folder.
        /// </summary>
        [RepositoryFolder("66ff426a-88db-42c0-9ee0-7ba677f8ca2f")]
        public virtual WordPress_WebRepositoryFolders.WordPress_Blog_PageAppFolder WordPress_Blog_Page
        {
            get { return _wordpress_blog_page; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class WordPress_WebRepositoryFolders
    {
        /// <summary>
        /// The WordPress_Login_PageAppFolder folder.
        /// </summary>
        [RepositoryFolder("c5c0629b-cf07-4542-bacf-9ed51373a673")]
        public partial class WordPress_Login_PageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _login_tbxInfo;
            RepoItemInfo _password_tbxInfo;
            RepoItemInfo _login_btnInfo;

            /// <summary>
            /// Creates a new WordPress_Login_Page  folder.
            /// </summary>
            public WordPress_Login_PageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WordPress_Login_Page", "/dom[@browsername='Chrome']", parentFolder, 30000, null, false, "c5c0629b-cf07-4542-bacf-9ed51373a673", "")
            {
                _login_tbxInfo = new RepoItemInfo(this, "login_tbx", ".//input[#'user_login']", "", 5000, null, "3998301e-cebf-434a-80ac-e9c7c18215ac");
                _password_tbxInfo = new RepoItemInfo(this, "password_tbx", ".//input[#'user_pass']", "", 5000, null, "54797184-5dd6-48fc-80c1-76bfaa79e261");
                _login_btnInfo = new RepoItemInfo(this, "login_btn", ".//input[#'wp-submit']", "", 5000, null, "10cbeb94-7e3e-4e33-93c9-edbb626fd7a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c5c0629b-cf07-4542-bacf-9ed51373a673")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c5c0629b-cf07-4542-bacf-9ed51373a673")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The login_tbx item.
            /// </summary>
            [RepositoryItem("3998301e-cebf-434a-80ac-e9c7c18215ac")]
            public virtual Ranorex.InputTag login_tbx
            {
                get
                {
                    return _login_tbxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The login_tbx item info.
            /// </summary>
            [RepositoryItemInfo("3998301e-cebf-434a-80ac-e9c7c18215ac")]
            public virtual RepoItemInfo login_tbxInfo
            {
                get
                {
                    return _login_tbxInfo;
                }
            }

            /// <summary>
            /// The password_tbx item.
            /// </summary>
            [RepositoryItem("54797184-5dd6-48fc-80c1-76bfaa79e261")]
            public virtual Ranorex.InputTag password_tbx
            {
                get
                {
                    return _password_tbxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The password_tbx item info.
            /// </summary>
            [RepositoryItemInfo("54797184-5dd6-48fc-80c1-76bfaa79e261")]
            public virtual RepoItemInfo password_tbxInfo
            {
                get
                {
                    return _password_tbxInfo;
                }
            }

            /// <summary>
            /// The login_btn item.
            /// </summary>
            [RepositoryItem("10cbeb94-7e3e-4e33-93c9-edbb626fd7a1")]
            public virtual Ranorex.InputTag login_btn
            {
                get
                {
                    return _login_btnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The login_btn item info.
            /// </summary>
            [RepositoryItemInfo("10cbeb94-7e3e-4e33-93c9-edbb626fd7a1")]
            public virtual RepoItemInfo login_btnInfo
            {
                get
                {
                    return _login_btnInfo;
                }
            }
        }

        /// <summary>
        /// The Chrome_WebAppFolder folder.
        /// </summary>
        [RepositoryFolder("adb87cfd-4e0a-4358-bd98-96f3a95b49cb")]
        public partial class Chrome_WebAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Chrome_Web  folder.
            /// </summary>
            public Chrome_WebAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome_Web", "/dom[@browsername='Chrome']", parentFolder, 5000, null, true, "adb87cfd-4e0a-4358-bd98-96f3a95b49cb", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("adb87cfd-4e0a-4358-bd98-96f3a95b49cb")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("adb87cfd-4e0a-4358-bd98-96f3a95b49cb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The WordPress_Main_PageAppFolder folder.
        /// </summary>
        [RepositoryFolder("f7e264bd-8534-45b8-965e-65fc2f86c78b")]
        public partial class WordPress_Main_PageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _title_tbxInfo;
            RepoItemInfo _posts_linkInfo;
            RepoItemInfo _add_new_linkInfo;
            RepoItemInfo _publish_btnInfo;
            RepoItemInfo _content_tbxInfo;
            RepoItemInfo _permalink_lblInfo;
            RepoItemInfo _view_post_btnInfo;
            RepoItemInfo _home_linkInfo;
            RepoItemInfo _all_posts_linkInfo;
            RepoItemInfo _move_to_trash_linkInfo;
            RepoItemInfo _remove_post_messageInfo;
            RepoItemInfo _edit_post_linkInfo;
            RepoItemInfo _trash_linkInfo;
            RepoItemInfo _all_title_checkboxInfo;
            RepoItemInfo _apply_to_delete_all_btnInfo;
            RepoItemInfo _action_cbbInfo;
            RepoItemInfo _remove_all_posts_messageInfo;
            RepoItemInfo _post_published_messageInfo;
            RepoItemInfo _my_account_linkInfo;
            RepoItemInfo _log_out_linkInfo;

            /// <summary>
            /// Creates a new WordPress_Main_Page  folder.
            /// </summary>
            public WordPress_Main_PageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WordPress_Main_Page", "/dom[@browsername='Chrome']", parentFolder, 5000, null, false, "f7e264bd-8534-45b8-965e-65fc2f86c78b", "")
            {
                _title_tbxInfo = new RepoItemInfo(this, "title_tbx", ".//input[#'title']", "", 5000, null, "f3db8993-60eb-4414-9b97-681e7f33bf15");
                _posts_linkInfo = new RepoItemInfo(this, "posts_link", ".//li[#'menu-posts']//div[@innertext='Posts']", "", 5000, null, "1d376da0-1cf2-4855-a965-591cddd3b1d3");
                _add_new_linkInfo = new RepoItemInfo(this, "add_new_link", ".//li[#'menu-posts']//a[@innertext='Add New']", "", 5000, null, "9b550187-389d-48c0-bc12-28d2315bedd2");
                _publish_btnInfo = new RepoItemInfo(this, "publish_btn", ".//input[#'publish']", "", 5000, null, "802f3a4c-f440-4cef-b987-d6b25b9a9f2e");
                _content_tbxInfo = new RepoItemInfo(this, "content_tbx", ".//textarea[#'content']", "", 5000, null, "53fc7297-763c-4a7e-bb17-10a3f8b4f780");
                _permalink_lblInfo = new RepoItemInfo(this, "permalink_lbl", ".//span[#'sample-permalink']", "", 5000, null, "6812ce44-395a-4553-b0d4-feaf8e83fb00");
                _view_post_btnInfo = new RepoItemInfo(this, "view_post_btn", ".//span[#'view-post-btn']/a[@innertext='View Post']", "", 5000, null, "3df57996-3411-4ddf-8e48-f7564a9ddd8c");
                _home_linkInfo = new RepoItemInfo(this, "home_link", ".//a[@innertext='Ranorex Webtest']", "", 5000, null, "e73415d0-1c9d-4f31-b573-a7c7cbbe778a");
                _all_posts_linkInfo = new RepoItemInfo(this, "all_posts_link", ".//li[#'menu-posts']//a[@innertext='All Posts']", "", 5000, null, "4beaec58-31fc-47cf-a63e-451e1beb4b42");
                _move_to_trash_linkInfo = new RepoItemInfo(this, "move_to_trash_link", ".//div[#'delete-action']/a[@innertext='Move to Trash']", "", 5000, null, "41e00144-96da-4a25-8cf5-d14e88c6c763");
                _remove_post_messageInfo = new RepoItemInfo(this, "remove_post_message", ".//div[#'message']/p[@innertext>'1 post moved to the Trash.']", "", 5000, null, "596ddef7-b253-4586-97ef-54f74f8a042d");
                _edit_post_linkInfo = new RepoItemInfo(this, "edit_post_link", ".//li[#'wp-admin-bar-edit']/a[@innertext='Edit Post']", "", 5000, null, "c7b6fb1b-2590-4612-97e8-44dd612708e8");
                _trash_linkInfo = new RepoItemInfo(this, "trash_link", ".//div[#'wpbody-content']//a[@innertext~'Trash']", "", 5000, null, "b8675659-e7d6-4e8d-90b0-8569bcf2562e");
                _all_title_checkboxInfo = new RepoItemInfo(this, "all_title_checkbox", ".//th[#'cb']/input[@type='checkbox']", "", 5000, null, "6102195d-6913-4c99-8e9b-3ea777cc8368");
                _apply_to_delete_all_btnInfo = new RepoItemInfo(this, "apply_to_delete_all_btn", ".//form[#'posts-filter']/div[1]//input[@tagvalue='Apply']", "", 5000, null, "342faa8f-2b11-45f1-ac4d-7f564138d7b3");
                _action_cbbInfo = new RepoItemInfo(this, "action_cbb", ".//form[#'posts-filter']//select[@name='action']", "", 5000, null, "cb8af2d5-00a2-4bbc-bb76-dc148bbd3bf1");
                _remove_all_posts_messageInfo = new RepoItemInfo(this, "remove_all_posts_message", ".//div[#'message']/p[@innertext~'permanently deleted']", "", 5000, null, "c2c556c1-46c1-4aa6-bb8f-fca87c00062d");
                _post_published_messageInfo = new RepoItemInfo(this, "post_published_message", ".//div[#'message']/p[@innertext='Post published. ']", "", 5000, null, "42354ecf-2498-4957-8aaf-b2b496aac714");
                _my_account_linkInfo = new RepoItemInfo(this, "my_account_link", ".//li[#'wp-admin-bar-my-account']/a[@innertext>'Howdy']", "", 5000, null, "5009920b-86e8-4840-8ed3-300c216bbb3a");
                _log_out_linkInfo = new RepoItemInfo(this, "log_out_link", ".//li[#'wp-admin-bar-logout']/a[@innertext='Log Out']", "", 5000, null, "4af00731-eaca-4d98-a2a5-a37bba65f04b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f7e264bd-8534-45b8-965e-65fc2f86c78b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f7e264bd-8534-45b8-965e-65fc2f86c78b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The title_tbx item.
            /// </summary>
            [RepositoryItem("f3db8993-60eb-4414-9b97-681e7f33bf15")]
            public virtual Ranorex.InputTag title_tbx
            {
                get
                {
                    return _title_tbxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The title_tbx item info.
            /// </summary>
            [RepositoryItemInfo("f3db8993-60eb-4414-9b97-681e7f33bf15")]
            public virtual RepoItemInfo title_tbxInfo
            {
                get
                {
                    return _title_tbxInfo;
                }
            }

            /// <summary>
            /// The posts_link item.
            /// </summary>
            [RepositoryItem("1d376da0-1cf2-4855-a965-591cddd3b1d3")]
            public virtual Ranorex.DivTag posts_link
            {
                get
                {
                    return _posts_linkInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The posts_link item info.
            /// </summary>
            [RepositoryItemInfo("1d376da0-1cf2-4855-a965-591cddd3b1d3")]
            public virtual RepoItemInfo posts_linkInfo
            {
                get
                {
                    return _posts_linkInfo;
                }
            }

            /// <summary>
            /// The add_new_link item.
            /// </summary>
            [RepositoryItem("9b550187-389d-48c0-bc12-28d2315bedd2")]
            public virtual Ranorex.ATag add_new_link
            {
                get
                {
                    return _add_new_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The add_new_link item info.
            /// </summary>
            [RepositoryItemInfo("9b550187-389d-48c0-bc12-28d2315bedd2")]
            public virtual RepoItemInfo add_new_linkInfo
            {
                get
                {
                    return _add_new_linkInfo;
                }
            }

            /// <summary>
            /// The publish_btn item.
            /// </summary>
            [RepositoryItem("802f3a4c-f440-4cef-b987-d6b25b9a9f2e")]
            public virtual Ranorex.InputTag publish_btn
            {
                get
                {
                    return _publish_btnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The publish_btn item info.
            /// </summary>
            [RepositoryItemInfo("802f3a4c-f440-4cef-b987-d6b25b9a9f2e")]
            public virtual RepoItemInfo publish_btnInfo
            {
                get
                {
                    return _publish_btnInfo;
                }
            }

            /// <summary>
            /// The content_tbx item.
            /// </summary>
            [RepositoryItem("53fc7297-763c-4a7e-bb17-10a3f8b4f780")]
            public virtual Ranorex.TextAreaTag content_tbx
            {
                get
                {
                    return _content_tbxInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The content_tbx item info.
            /// </summary>
            [RepositoryItemInfo("53fc7297-763c-4a7e-bb17-10a3f8b4f780")]
            public virtual RepoItemInfo content_tbxInfo
            {
                get
                {
                    return _content_tbxInfo;
                }
            }

            /// <summary>
            /// The permalink_lbl item.
            /// </summary>
            [RepositoryItem("6812ce44-395a-4553-b0d4-feaf8e83fb00")]
            public virtual Ranorex.SpanTag permalink_lbl
            {
                get
                {
                    return _permalink_lblInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The permalink_lbl item info.
            /// </summary>
            [RepositoryItemInfo("6812ce44-395a-4553-b0d4-feaf8e83fb00")]
            public virtual RepoItemInfo permalink_lblInfo
            {
                get
                {
                    return _permalink_lblInfo;
                }
            }

            /// <summary>
            /// The view_post_btn item.
            /// </summary>
            [RepositoryItem("3df57996-3411-4ddf-8e48-f7564a9ddd8c")]
            public virtual Ranorex.ATag view_post_btn
            {
                get
                {
                    return _view_post_btnInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The view_post_btn item info.
            /// </summary>
            [RepositoryItemInfo("3df57996-3411-4ddf-8e48-f7564a9ddd8c")]
            public virtual RepoItemInfo view_post_btnInfo
            {
                get
                {
                    return _view_post_btnInfo;
                }
            }

            /// <summary>
            /// The home_link item.
            /// </summary>
            [RepositoryItem("e73415d0-1c9d-4f31-b573-a7c7cbbe778a")]
            public virtual Ranorex.ATag home_link
            {
                get
                {
                    return _home_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The home_link item info.
            /// </summary>
            [RepositoryItemInfo("e73415d0-1c9d-4f31-b573-a7c7cbbe778a")]
            public virtual RepoItemInfo home_linkInfo
            {
                get
                {
                    return _home_linkInfo;
                }
            }

            /// <summary>
            /// The all_posts_link item.
            /// </summary>
            [RepositoryItem("4beaec58-31fc-47cf-a63e-451e1beb4b42")]
            public virtual Ranorex.ATag all_posts_link
            {
                get
                {
                    return _all_posts_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The all_posts_link item info.
            /// </summary>
            [RepositoryItemInfo("4beaec58-31fc-47cf-a63e-451e1beb4b42")]
            public virtual RepoItemInfo all_posts_linkInfo
            {
                get
                {
                    return _all_posts_linkInfo;
                }
            }

            /// <summary>
            /// The move_to_trash_link item.
            /// </summary>
            [RepositoryItem("41e00144-96da-4a25-8cf5-d14e88c6c763")]
            public virtual Ranorex.ATag move_to_trash_link
            {
                get
                {
                    return _move_to_trash_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The move_to_trash_link item info.
            /// </summary>
            [RepositoryItemInfo("41e00144-96da-4a25-8cf5-d14e88c6c763")]
            public virtual RepoItemInfo move_to_trash_linkInfo
            {
                get
                {
                    return _move_to_trash_linkInfo;
                }
            }

            /// <summary>
            /// The remove_post_message item.
            /// </summary>
            [RepositoryItem("596ddef7-b253-4586-97ef-54f74f8a042d")]
            public virtual Ranorex.PTag remove_post_message
            {
                get
                {
                    return _remove_post_messageInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The remove_post_message item info.
            /// </summary>
            [RepositoryItemInfo("596ddef7-b253-4586-97ef-54f74f8a042d")]
            public virtual RepoItemInfo remove_post_messageInfo
            {
                get
                {
                    return _remove_post_messageInfo;
                }
            }

            /// <summary>
            /// The edit_post_link item.
            /// </summary>
            [RepositoryItem("c7b6fb1b-2590-4612-97e8-44dd612708e8")]
            public virtual Ranorex.ATag edit_post_link
            {
                get
                {
                    return _edit_post_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The edit_post_link item info.
            /// </summary>
            [RepositoryItemInfo("c7b6fb1b-2590-4612-97e8-44dd612708e8")]
            public virtual RepoItemInfo edit_post_linkInfo
            {
                get
                {
                    return _edit_post_linkInfo;
                }
            }

            /// <summary>
            /// The trash_link item.
            /// </summary>
            [RepositoryItem("b8675659-e7d6-4e8d-90b0-8569bcf2562e")]
            public virtual Ranorex.ATag trash_link
            {
                get
                {
                    return _trash_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The trash_link item info.
            /// </summary>
            [RepositoryItemInfo("b8675659-e7d6-4e8d-90b0-8569bcf2562e")]
            public virtual RepoItemInfo trash_linkInfo
            {
                get
                {
                    return _trash_linkInfo;
                }
            }

            /// <summary>
            /// The all_title_checkbox item.
            /// </summary>
            [RepositoryItem("6102195d-6913-4c99-8e9b-3ea777cc8368")]
            public virtual Ranorex.InputTag all_title_checkbox
            {
                get
                {
                    return _all_title_checkboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The all_title_checkbox item info.
            /// </summary>
            [RepositoryItemInfo("6102195d-6913-4c99-8e9b-3ea777cc8368")]
            public virtual RepoItemInfo all_title_checkboxInfo
            {
                get
                {
                    return _all_title_checkboxInfo;
                }
            }

            /// <summary>
            /// The apply_to_delete_all_btn item.
            /// </summary>
            [RepositoryItem("342faa8f-2b11-45f1-ac4d-7f564138d7b3")]
            public virtual Ranorex.InputTag apply_to_delete_all_btn
            {
                get
                {
                    return _apply_to_delete_all_btnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The apply_to_delete_all_btn item info.
            /// </summary>
            [RepositoryItemInfo("342faa8f-2b11-45f1-ac4d-7f564138d7b3")]
            public virtual RepoItemInfo apply_to_delete_all_btnInfo
            {
                get
                {
                    return _apply_to_delete_all_btnInfo;
                }
            }

            /// <summary>
            /// The action_cbb item.
            /// </summary>
            [RepositoryItem("cb8af2d5-00a2-4bbc-bb76-dc148bbd3bf1")]
            public virtual Ranorex.SelectTag action_cbb
            {
                get
                {
                    return _action_cbbInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The action_cbb item info.
            /// </summary>
            [RepositoryItemInfo("cb8af2d5-00a2-4bbc-bb76-dc148bbd3bf1")]
            public virtual RepoItemInfo action_cbbInfo
            {
                get
                {
                    return _action_cbbInfo;
                }
            }

            /// <summary>
            /// The remove_all_posts_message item.
            /// </summary>
            [RepositoryItem("c2c556c1-46c1-4aa6-bb8f-fca87c00062d")]
            public virtual Ranorex.PTag remove_all_posts_message
            {
                get
                {
                    return _remove_all_posts_messageInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The remove_all_posts_message item info.
            /// </summary>
            [RepositoryItemInfo("c2c556c1-46c1-4aa6-bb8f-fca87c00062d")]
            public virtual RepoItemInfo remove_all_posts_messageInfo
            {
                get
                {
                    return _remove_all_posts_messageInfo;
                }
            }

            /// <summary>
            /// The post_published_message item.
            /// </summary>
            [RepositoryItem("42354ecf-2498-4957-8aaf-b2b496aac714")]
            public virtual Ranorex.PTag post_published_message
            {
                get
                {
                    return _post_published_messageInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The post_published_message item info.
            /// </summary>
            [RepositoryItemInfo("42354ecf-2498-4957-8aaf-b2b496aac714")]
            public virtual RepoItemInfo post_published_messageInfo
            {
                get
                {
                    return _post_published_messageInfo;
                }
            }

            /// <summary>
            /// The my_account_link item.
            /// </summary>
            [RepositoryItem("5009920b-86e8-4840-8ed3-300c216bbb3a")]
            public virtual Ranorex.ATag my_account_link
            {
                get
                {
                    return _my_account_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The my_account_link item info.
            /// </summary>
            [RepositoryItemInfo("5009920b-86e8-4840-8ed3-300c216bbb3a")]
            public virtual RepoItemInfo my_account_linkInfo
            {
                get
                {
                    return _my_account_linkInfo;
                }
            }

            /// <summary>
            /// The log_out_link item.
            /// </summary>
            [RepositoryItem("4af00731-eaca-4d98-a2a5-a37bba65f04b")]
            public virtual Ranorex.ATag log_out_link
            {
                get
                {
                    return _log_out_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The log_out_link item info.
            /// </summary>
            [RepositoryItemInfo("4af00731-eaca-4d98-a2a5-a37bba65f04b")]
            public virtual RepoItemInfo log_out_linkInfo
            {
                get
                {
                    return _log_out_linkInfo;
                }
            }
        }

        /// <summary>
        /// The WordPress_Blog_PageAppFolder folder.
        /// </summary>
        [RepositoryFolder("66ff426a-88db-42c0-9ee0-7ba677f8ca2f")]
        public partial class WordPress_Blog_PageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _title_lblInfo;

            /// <summary>
            /// Creates a new WordPress_Blog_Page  folder.
            /// </summary>
            public WordPress_Blog_PageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WordPress_Blog_Page", "/dom[@browsername='Chrome']", parentFolder, 5000, null, false, "66ff426a-88db-42c0-9ee0-7ba677f8ca2f", "")
            {
                _title_lblInfo = new RepoItemInfo(this, "title_lbl", ".//h1[#'pagetitle']", "", 5000, null, "ef6cdd89-e77d-4922-9184-386d5eb639dc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("66ff426a-88db-42c0-9ee0-7ba677f8ca2f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("66ff426a-88db-42c0-9ee0-7ba677f8ca2f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The title_lbl item.
            /// </summary>
            [RepositoryItem("ef6cdd89-e77d-4922-9184-386d5eb639dc")]
            public virtual Ranorex.H1Tag title_lbl
            {
                get
                {
                    return _title_lblInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The title_lbl item info.
            /// </summary>
            [RepositoryItemInfo("ef6cdd89-e77d-4922-9184-386d5eb639dc")]
            public virtual RepoItemInfo title_lblInfo
            {
                get
                {
                    return _title_lblInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
