///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Chrome_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validation recording.
    /// </summary>
    [TestModule("5ab430a7-28be-4e60-b96f-decbbec00186", ModuleType.Recording, 1)]
    public partial class Validation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Chrome_TestRepository repository.
        /// </summary>
        public static Chrome_TestRepository repo = Chrome_TestRepository.Instance;

        static Validation instance = new Validation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validation()
        {
            search_result = "";
            return_value = "";
            search_name = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validation Instance
        {
            get { return instance; }
        }

#region Variables

        string _search_result;

        /// <summary>
        /// Gets or sets the value of variable search_result.
        /// </summary>
        [TestVariable("ff94df8f-109f-45aa-933d-4c39a0d682d6")]
        public string search_result
        {
            get { return _search_result; }
            set { _search_result = value; }
        }

        string _return_value;

        /// <summary>
        /// Gets or sets the value of variable return_value.
        /// </summary>
        [TestVariable("4ea01ca9-6c1f-4dda-943a-b21101678328")]
        public string return_value
        {
            get { return _return_value; }
            set { _return_value = value; }
        }

        string _search_name;

        /// <summary>
        /// Gets or sets the value of variable search_name.
        /// </summary>
        [TestVariable("9c9ae587-ae5e-445a-b85b-efb576021a61")]
        public string search_name
        {
            get { return _search_name; }
            set { _search_name = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'Search_Result_window'.", repo.Search_Result_window.SelfInfo, new RecordItemIndex(0));
            repo.Search_Result_window.Self.EnsureVisible();
            Delay.Milliseconds(0);
            
            try {
                Get_value_search_result_textbox1(null);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Validate_search_result_textbox1(null);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
