///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Excel_Test
{
    public partial class CloseAUT
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_dont_save_button(RepoItemInfo buttonInfo)
        {
        	bool btnDontSaveExist = buttonInfo.Exists();
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at 38;13.", buttonInfo);
            
            if (btnDontSaveExist) {
            	buttonInfo.FindAdapter<Button>().Click("38;13");
            }
            
            
        }

        public void Mouse_Click_close_button(RepoItemInfo buttonInfo)
        {
        	bool btnCloseExist = buttonInfo.Exists();
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at 12;8.", buttonInfo);
            
            if (btnCloseExist) {
            	buttonInfo.FindAdapter<Button>().Click("12;8");
            }
            
        }

    }
}
